### ISSUE TITLE
Support for Cosmetic Armor Reworked 1.8.9

### ISSUE THREAD

**Issue by Hydrargiros** [benblank/Ice#4]
Mod is awesome. No silly tomb, 1 block, really really nice. I want to add it to the modpacks, but im a great fan of cosmetic armours, and after some testing, the mod dont store the cosmetic.

I would really apreciate if you have some free time to add support for this mod.
http://minecraft.curseforge.com/projects/cosmetic-armor-reworked?gameCategorySlug=mc-mods&projectID=237307

Thanks for your time. ☿

**Comment by benblank** [comment]
Looks pretty simple.  Let me give it a shot!

**Comment by Hydrargiros** [comment]
Thanks for your time :)

**Comment by benblank** [comment]
Fortunately, CAR makes it pretty easy to integrate with.  Release 1.1.4 contains support for it.  :-)

**Comment by Hydrargiros** [comment]
Thanks for the help, really appreciate your time. your mod is awesome. keep doing.
