### ISSUE TITLE
Server crash.   Contact authors of the following mods:    Ice

### ISSUE THREAD

**Issue by Hydrargiros** [benblank/Ice#5]
Its me again. my server tells me to give you this gift. sorry for the inconvenience
[crash-2016-02-22_04.15.59-server.txt](https://github.com/benblank/Ice/files/140058/crash-2016-02-22_04.15.59-server.txt)

In client, all works fine, but in server seems ICE crash something. But my code skill not so good, just easy java for modpacks.

**Comment by benblank** [comment]
I'm not able to reproduce that error, but it seems to be related to the version of Java you're using.  I see from the log that the server is running on Java 7 (version 1.7.0_95).  Make sure that you're running Java 8 — and _only_ Java 8 — on your server and see if the problem still occurs.

**Comment by Hydrargiros** [comment]
Java Version: 1.7.0_95 , yep, should need to update it. thanks for your time, you are really kind.
Will tell my more skilled friend to update server and stuff when he get the time. It worked fine until i update it today with some new mods and new forge.

Will be back with more info when i get the java change. Thanks again for your time.

**Comment by Hydrargiros** [comment]
Changed java to 8, all go fine. Thanks for your help! and your time.

**Comment by benblank** [comment]
Glad you were able to get it working!
