### ISSUE TITLE
Death by suffocation and lava

### ISSUE THREAD

**Issue by Hydrargiros** [benblank/Ice#6]
Its me again.

I was doing stuff with a friend in the server, when i use my thaumcraft portable hole wand and my friend fall to the hole, were he died by suffocation.
It seems (after some checking) That the grave didnt spawn in these cases, were there is no near air block. (The closest corridor was  2 or 3 blocks away).

If you die in lava, you also dont get a grave, but dont know if that is intended.(You die in lava, you loose everything as normal)

**Comment by benblank** [comment]
Definitely not intended. If you suffocate, ICE tries to find air to out your death marker in, so it may appear in a nearby cave (within 16 blocks). When you die in lava, it should replace the lava, which may submerge it.

I'll double-check these when I get home and test the portable hole, too.

**Comment by Hydrargiros** [comment]
He died because portable hole just finish and he was inside a block, i have check the caves arround and in top and didnt find tomb. will double check.

**Comment by benblank** [comment]
I just tested suffocating when a portable hole collapse in both SSP and SMP and it **does** create a death marker; you may just need to look around for it (again, up to 16 blocks away on all three axes; I should probably turn that down).

There is definitely a bug with lava, though.  I'll start working on a fix right away.

**Comment by Hydrargiros** [comment]
Im diggin up a cube to find the tomb.
May the lava near the death point can count to do not spawn? 
there was lava just in the closest air spot were death

**Comment by benblank** [comment]
That's entirely possible.  If ICE found the lava as the first available spot, the death marker would have spawned there and then been destroyed by the lava.  :-(

**Comment by benblank** [comment]
Okay!  I've released 1.1.5 to both fix the lava/water bug and to make suffocation markers easier to find.  Now, ICE will only look up to four blocks away and the server log will show its exact coordinates.

**Comment by Hydrargiros** [comment]
Cool,Thanks again for your mod support.
 if there is no air near 4 blocks, will it search far away, or change stone for marker?

**Comment by benblank** [comment]
If it can't find an open space, it'll just place the marker right where you died.  It's mostly to avoid damaging the machinery if you die in the middle of your ore processor or ME system or some such.

**Comment by Hydrargiros** [comment]
Ok. Thanks for all. Will be back if i find more things :)
